apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: 2018-10-18T21:52:13Z
  generation: 2
  labels:
    app: ocagent-trace
  name: ocagent-trace
  namespace: default
  resourceVersion: "22677"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/ocagent-trace
  uid: 12848991-d320-11e8-82c7-42010a800002
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ocagent-trace
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ocagent-trace
    spec:
      containers:
      - image: gcr.io/samnaser-gke-dev-217421/ocagent:v3
        imagePullPolicy: IfNotPresent
        name: ocagent-trace
        ports:
        - containerPort: 55678
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30